#!/bin/bash

echo -e "\033[1m\033[4mSHELL PROJECT AUTHORS\033[0m" > AUTHORS
echo "This file lists all the contributors on this project:" >> AUTHORS
echo "" >> AUTHORS

#this will get the list of authors from the git log
git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf >> AUTHORS

echo "" >> AUTHORS
echo "Generated by $(basename $0)" >> AUTHORS
